# Lefthook configuration for MeOS Graphics
# Runs checks before git commits to catch issues early

pre-commit:
  parallel: true
  commands:
    build:
      run: go build -v ./...
      tags: build compile
      skip:
        - merge
        - rebase
    
    test:
      run: go test -v ./...
      tags: test unit
      skip:
        - merge
        - rebase
    
    lint:
      run: golangci-lint run --timeout=5m
      tags: lint style
      skip:
        - merge
        - rebase
    
    docs-check:
      run: |
        go run ./cmd/generate-docs
        if ! git diff --quiet docs/CLI_FLAGS.md; then
          echo "CLI documentation is out of date. The updated docs have been generated."
          echo "Please add the changes to your commit."
          exit 1
        fi
      tags: docs documentation cli
      skip:
        - merge
        - rebase
    
    swagger-check:
      run: |
        # Install swag if not present
        if ! command -v swag &> /dev/null; then
          go install github.com/swaggo/swag/cmd/swag@latest
        fi
        
        # Generate swagger docs
        swag init -g cmd/meos-graphics/main.go --parseDependency --parseInternal
        
        # Validate that generated docs match source annotations
        ./scripts/validate-swagger.sh
        
        # Check if docs changed
        if ! git diff --quiet docs/swagger.json docs/swagger.yaml docs/docs.go; then
          echo "Swagger documentation is out of date. The updated docs have been generated."
          echo "Please add the changes to your commit."
          exit 1
        fi
      tags: docs documentation swagger api
      skip:
        - merge
        - rebase

# Optional: run specific checks with tags
# lefthook run pre-commit --tags=build,test