basePath: /
definitions:
  service.ClassInfo:
    properties:
      id:
        type: integer
      name:
        type: string
      orderKey:
        type: integer
    type: object
  service.ResultEntry:
    properties:
      club:
        type: string
      difference:
        description: Formatted duration from leader
        type: string
      name:
        type: string
      position:
        type: integer
      runningTime:
        description: Formatted duration string
        type: string
      status:
        type: string
    type: object
  service.SplitStanding:
    properties:
      controlId:
        type: integer
      controlName:
        type: string
      standings:
        items:
          $ref: '#/definitions/service.SplitTime'
        type: array
    type: object
  service.SplitTime:
    properties:
      club:
        type: string
      elapsedTime:
        type: string
      name:
        type: string
      position:
        type: integer
      timeDifference:
        type: string
    type: object
  service.SplitsResponse:
    properties:
      className:
        type: string
      splits:
        items:
          $ref: '#/definitions/service.SplitStanding'
        type: array
    type: object
  service.StartListEntry:
    properties:
      club:
        type: string
      name:
        type: string
      startTime:
        description: Formatted as HH:mm
        type: string
    type: object
host: localhost:8090
info:
  contact:
    email: malthe@grundtvigsvej.dk
    name: '@malpou'
    url: https://github.com/MetsaApp/meos-graphics
  description: REST API for accessing orienteering competition data from MeOS
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: meos-graphics
  version: 1.2.0 # x-release-please-version
paths:
  /classes:
    get:
      consumes:
      - application/json
      description: Get a list of all competition classes sorted by order key
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.ClassInfo'
            type: array
      summary: Get all competition classes
      tags:
      - classes
  /classes/{classId}/results:
    get:
      consumes:
      - application/json
      description: Get the results for a specific competition class including positions
        and times
      parameters:
      - description: Class ID
        in: path
        name: classId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.ResultEntry'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get results for a class
      tags:
      - classes
  /classes/{classId}/splits:
    get:
      consumes:
      - application/json
      description: Get split times at each control for a specific competition class
      parameters:
      - description: Class ID
        in: path
        name: classId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.SplitsResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get split times for a class
      tags:
      - classes
  /classes/{classId}/startlist:
    get:
      consumes:
      - application/json
      description: Get the start list for a specific competition class
      parameters:
      - description: Class ID
        in: path
        name: classId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.StartListEntry'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get start list for a class
      tags:
      - classes
schemes:
- http
- https
swagger: "2.0"
