name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Install templ
      run: go install github.com/a-h/templ/cmd/templ@latest
    
    - name: Generate templ files
      run: templ generate
        
    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: go test -v ./...
      
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m
        
    - name: Check CLI documentation is up-to-date
      run: |
        go run ./cmd/generate-docs
        git diff --exit-code docs/CLI_FLAGS.md || \
          (echo "CLI documentation is out of date. Run 'go run ./cmd/generate-docs' and commit the changes." && exit 1)
    
    - name: Install swag
      run: go install github.com/swaggo/swag/cmd/swag@latest
    
    - name: Check Swagger documentation is up-to-date
      run: |
        swag init -g cmd/meos-graphics/main.go --parseDependency --parseInternal
        ./scripts/validate-swagger.sh
        git diff --exit-code docs/swagger.json docs/swagger.yaml docs/docs.go || \
          (echo "Swagger documentation is out of date. Run 'swag init -g cmd/meos-graphics/main.go' and commit the changes." && exit 1)