name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: go test -v ./...
      
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m
        
    - name: Check documentation is up-to-date
      run: |
        go run ./cmd/generate-docs
        git diff --exit-code docs/CLI_FLAGS.md || \
          (echo "Documentation is out of date. Run 'go run ./cmd/generate-docs' and commit the changes." && exit 1)